Add Event lookup
Borewit/musicbrainz-api pull request #518
Opened 2022-07-21 10:03 UTC by Haschikeks

Add new Lookup Function for [Event](https://musicbrainz.org/doc/Event)

This PR is connected to #3

2022-07-24 15:57 UTC, Borewit requested changes

2022-07-24 15:57 UTC, Borewit commented on src/musicbrainz-api.ts
> +   * @param inc EventIncludes
I suggest clear parameter names
```suggestion
   * @param eventIncludes EventIncludes
```

2022-07-24 15:57 UTC, Borewit commented on src/musicbrainz-api.ts
> +   * @param inc EventIncludes
```suggestion
   * @param inc List of sub-queries to enable
```

2022-07-25 10:08 UTC, Haschikeks reviewed
Updated parameter names

2022-07-25 14:18 UTC, Borewit approved these changes

2022-07-25 14:18 UTC, merged

2022-07-25 14:21 UTC, Borewit commented
We need to describe new functionality in the README, realized just after merging